from .ontology_init_prompt import ONTOLOGY_INIT_PROMPT
from .interface_prompt import INTERFACE_AGENT_PROMPT
from .human_preference_prompt import HUMAN_PREFERENCE_PROMPT
from .schema_design_prompt import SCHEMA_DESIGN_PROMPT
from .schema_generation_prompt import SCHEMA_GENERATION_PROMPT
from .doc_distiller_prompt import DOC_DISTILLER_PROMPT
from .mention_detection_prompt import MENTION_DETECTION_PROMPT
from .relation_extraction_prompt import RELATION_EXTRACTION_PROMPT